### ISSUE TITLE
Roses example failing to build

### ISSUE THREAD

**Issue by james-r-smith** [material-components/material-components-web-react#582]
I'm starting out with front-end development, and so I'm not sure what the reason for this issue is. It seems to be a problem with the Babel plugin `transform-class-properties` that it's inheriting from the root of the repository? I've tried on node versions `10.4.0` and `11.5.0` and both have given me the same error. Any help is appreciated. Thanks!

Output:

```
$ npm start

> @ start /Users/<USER>/work/js/material-components-web-react/examples/roses
> webpack-dev-server

Project is running at http://localhost:8080/
webpack output is served from /
Hash: d06901bed2c2ee04faad
Version: webpack 3.12.0
Time: 350ms
    Asset     Size  Chunks             Chunk Names
bundle.js  8.04 kB       0  [emitted]  main
   [0] multi (webpack)-dev-server/client?http://localhost:8080 babel-polyfill ./index.js 52 bytes {0} [built]
   [1] (webpack)-dev-server/client?http://localhost:8080 1.76 kB {0} [built] [failed] [1 error]
   [2] ./node_modules/babel-polyfill/lib/index.js 1.76 kB {0} [built] [failed] [1 error]
   [3] ./index.js 1.76 kB {0} [built] [failed] [1 error]

ERROR in ./index.js
Module build failed: ReferenceError: Unknown plugin "transform-class-properties" specified in "/Users/<USER>/work/js/material-components-web-react/.babelrc" at 0, attempted to resolve relative to "/Users/<USER>/work/js/material-components-web-react"
    at /Users/<USER>/work/js/material-components-web-react/examples/roses/node_modules/babel-core/lib/transformation/file/options/option-manager.js:180:17
    at Array.map (<anonymous>)
    at Function.normalisePlugins (/Users/<USER>/work/js/material-components-web-react/examples/roses/node_modules/babel-core/lib/transformation/file/options/option-manager.js:158:20)
    at OptionManager.mergeOptions (/Users/<USER>/work/js/material-components-web-react/examples/roses/node_modules/babel-core/lib/transformation/file/options/option-manager.js:234:36)
    at OptionManager.init (/Users/<USER>/work/js/material-components-web-react/examples/roses/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
    at File.initOptions (/Users/<USER>/work/js/material-components-web-react/examples/roses/node_modules/babel-core/lib/transformation/file/index.js:212:65)
    at new File (/Users/<USER>/work/js/material-components-web-react/examples/roses/node_modules/babel-core/lib/transformation/file/index.js:135:24)
    at Pipeline.transform (/Users/<USER>/work/js/material-components-web-react/examples/roses/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at transpile (/Users/<USER>/work/js/material-components-web-react/examples/roses/node_modules/babel-loader/lib/index.js:50:20)
    at Object.module.exports (/Users/<USER>/work/js/material-components-web-react/examples/roses/node_modules/babel-loader/lib/index.js:173:20)
 @ multi (webpack)-dev-server/client?http://localhost:8080 babel-polyfill ./index.js

ERROR in (webpack)-dev-server/client?http://localhost:8080
Module build failed: ReferenceError: Unknown plugin "transform-class-properties" specified in "/Users/<USER>/work/js/material-components-web-react/.babelrc" at 0, attempted to resolve relative to "/Users/<USER>/work/js/material-components-web-react"
    at /Users/<USER>/work/js/material-components-web-react/examples/roses/node_modules/babel-core/lib/transformation/file/options/option-manager.js:180:17
    at Array.map (<anonymous>)
    at Function.normalisePlugins (/Users/<USER>/work/js/material-components-web-react/examples/roses/node_modules/babel-core/lib/transformation/file/options/option-manager.js:158:20)
    at OptionManager.mergeOptions (/Users/<USER>/work/js/material-components-web-react/examples/roses/node_modules/babel-core/lib/transformation/file/options/option-manager.js:234:36)
    at OptionManager.init (/Users/<USER>/work/js/material-components-web-react/examples/roses/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
    at File.initOptions (/Users/<USER>/work/js/material-components-web-react/examples/roses/node_modules/babel-core/lib/transformation/file/index.js:212:65)
    at new File (/Users/<USER>/work/js/material-components-web-react/examples/roses/node_modules/babel-core/lib/transformation/file/index.js:135:24)
    at Pipeline.transform (/Users/<USER>/work/js/material-components-web-react/examples/roses/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at transpile (/Users/<USER>/work/js/material-components-web-react/examples/roses/node_modules/babel-loader/lib/index.js:50:20)
    at Object.module.exports (/Users/<USER>/work/js/material-components-web-react/examples/roses/node_modules/babel-loader/lib/index.js:173:20)
 @ multi (webpack)-dev-server/client?http://localhost:8080 babel-polyfill ./index.js

ERROR in ./node_modules/babel-polyfill/lib/index.js
Module build failed: ReferenceError: Unknown plugin "transform-class-properties" specified in "/Users/<USER>/work/js/material-components-web-react/.babelrc" at 0, attempted to resolve relative to "/Users/<USER>/work/js/material-components-web-react"
    at /Users/<USER>/work/js/material-components-web-react/examples/roses/node_modules/babel-core/lib/transformation/file/options/option-manager.js:180:17
    at Array.map (<anonymous>)
    at Function.normalisePlugins (/Users/<USER>/work/js/material-components-web-react/examples/roses/node_modules/babel-core/lib/transformation/file/options/option-manager.js:158:20)
    at OptionManager.mergeOptions (/Users/<USER>/work/js/material-components-web-react/examples/roses/node_modules/babel-core/lib/transformation/file/options/option-manager.js:234:36)
    at OptionManager.init (/Users/<USER>/work/js/material-components-web-react/examples/roses/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
    at File.initOptions (/Users/<USER>/work/js/material-components-web-react/examples/roses/node_modules/babel-core/lib/transformation/file/index.js:212:65)
    at new File (/Users/<USER>/work/js/material-components-web-react/examples/roses/node_modules/babel-core/lib/transformation/file/index.js:135:24)
    at Pipeline.transform (/Users/<USER>/work/js/material-components-web-react/examples/roses/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at transpile (/Users/<USER>/work/js/material-components-web-react/examples/roses/node_modules/babel-loader/lib/index.js:50:20)
    at Object.module.exports (/Users/<USER>/work/js/material-components-web-react/examples/roses/node_modules/babel-loader/lib/index.js:173:20)
 @ multi (webpack)-dev-server/client?http://localhost:8080 babel-polyfill ./index.js
webpack: Failed to compile.
```

**Comment by moog16** [comment]
Did you `npm install` in both the root directory and the `/examples/roses` directory? Can you write out your steps so that I can try to reproduce this error? I currently am on node version `10.13.0`.

**Comment by james-r-smith** [comment]
Hey @moog16, it was that I didn't build the root directory! 🤦‍♂️ Thanks a bunch. 👍

**Comment by moog16** [comment]
Glad you got it working!
